# Capítulo III: Caracterización del Movimiento Sísmico {.unnumbered}

-   La sección 1 se ocupa del minado de datos y el control de calidad de los datos. En este capítlo el objetivo es compilar catálogos y bases de datos de diferentes regiones del mundo. En esta etapa se identificarán los registros válidos a partir de un anállisis de integridad y calidad de los metadatos y se eliminarán todos los registros que no cumplan con ciertos criterios mínimos de aceptación (QC) basados básicamente en la cantidad de metadatos asociados al registro, tales como las condiciones geotécnicas de la estación de registro, los datos de magnitud y distancias del evento sísmico y . El aporte de este capítulo serán una base de datos relacional eventos, estaciones, y registros sísmicos asociados a cada evento y estación.

-   La sección 2, plantea los algoritmos fundamentales requeridos para el procesamiento de series temporales asociadas a eventos śismicos. El procesamiento incluirá el re-muestreo (resampling), la aplicación de filtros pasa-banda, la eliminación de valores medios (DC) , tendencias (trends) y saltos (glitch), el recorte de las duraciones efectivas y la implementación de algoritmos robustos de integración de las series temporales. El aporte de este capítulo será una tabla de registros sísmicos normalizados en superficie y un algoritmo (librería) de código abierto para el procesamiento de registros sísmicos

-   La sección 3 se efocará en remover la respuesta dinámica del sitio de los registros sísmicos en superficie y consistirá básicamente en generar registros sísmicos en roca basal a partir de la simulación numérica de todos los posibles perfiles geotécnicos que puedan existir bajo una estación sismológica en particular, en la cual se conocen un cierto número de parámetros geotécnicos y dinámicos. A partir de los diferentes perfiles geotécnicos simulados, se impementará un sistema de clasificación de sitios a partir de un factor que combine la respuesta dinámica del sitio y las propiedades dinámicas del perfil geotécnico

-   La sección 4, aborda la parametrización de las series temporales normalizadas y regularizadas. El objetivo principal de eesta sección será esencialmente la identificación de los parámetros asociados a un modelo dinámico equivalente $\psi = \{ \psi_1,\psi_2,... \}$ mediante el análisis paramétrico de series temporales no-estacionarias en roca basal. Esta es la etapa define uno de los aportes más importantes del trabajo, ya que establece una representación paramétrica de los registros sísmicos regularizados y normalizados en roca basal \# Capítulo IV: Predicción de la Demanda Sísmica {.unnumbered}

-   La sección 1 incorpora la incertidumbre espacial y temporal de los movimientos sísmicos a partir de la clasificación supervisada de los registros sísmicos en términos de escenarios sísmicos. El objetivo de esta sección consistirá en desagregar los parámetros dinámicos del modelo equivalente $\psi = \{ \psi_1,\psi_2,... \}$ en diferentes escenarios sísmicos de magnitud y distancia a la fuente $\{M,R\}$ y estimar un conjunto de medidas de intensidad asociadas a cada escenario sísmico.

-   La sección 2, incorpora las características de la región y los mecanismos de generación y se ocupará principalmente de clasificar los parámetros dinámicos de series temporales no estacionarias, mediante metodologías de aprendizaje no-supervisado. El aporte de esta sección será un catálogo de sismos de diferentes regiones del mundo, agrupados por parámetros basados en modelos dinámicos obtenidos mediante aprendizaje automático y sin intervención humana (sesgo)

-   La sección 3, estudiará las meteodologías disponibles para la caracterizacion de las funciones de distribución del movimiento sísmico y de la demanda sísmica, y la implementación de modelos no paramétricos de predicción

-   La última sección del capíulo III, presenta un ejemplo de aplicación de la metodología propuesta sobre el mismo problema que se analizó en la introducción y se comparan algunas métricas de variabilidad

