---
# title: "Planteo"
# author: "Alejandro Verri Kozlowski"
# date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Estado Actual de la Práctica

### Definiciones

La ingeniería sísmica es el vínculo entre las ciencias de la tierra y la ingeniería civil. El principal aporte de la ingeniería sísmica al diseño en ingeniería es la definición de las acciones sísmicas (cargas, desplazamientos)en términos de su intensidad y frecuencia de ocurrencia durante la vida útil de una estructura.

La demanda sísmica de un sistema es el conjunto de parámetros que caracteriza la respuesta de un sistema dinámico cuando es sometido sujeto a movimientos sísmicos en la superficie de fundación y puede interpretarse como una expresión del movimiento sísmico en el sistema, en términos de fuerzas, distorsiones, esfuerzos, etc.

El sitio en donde se fundan las estructuras e instalaciones, puede considerarse en sí mismo como un sistema dinámico que responde cuando es sometido a movimientos sísmicos a nivel de roca basal. Este sistema tendrá propiedades dinámicas que dependeRÁNn de las propiedades mecánicas de los estratos de suelo apoyado sobre la roca basal.

Los movimientos sísmicos a nivel de la roca basal constituyen a su vez la respuesta dinámica de un sistema mucho más complejo de propagación de ondas elásticas sísmicas a través de las dierentes capas de la corteza terrestre, originado por el movimiento súbito de placas tectónicas que constituyen los eventos sísmicos.

La demanda es un parámetro de la respuesta sísmica del sistema (por ejemplo, el esfuerzo cortante de una columna, o el asentamiento de un terraplén inducidos por sismos) que puede asociarse a un objetivo de diseño y puede entenderse como una expresión del movimiento sísmico en ese sistema dinámico particular.

En un escenario determinístico, un modelo de estimación de la demanda sísmica requiere como mínimo cuatro pasos:

-   La estimación de la intensidad del movimiento sísmico a nivel de roca basal en el sitio del proyecto.
-   La estimación de la intensidad del movimiento sísmico a nivel de superficie, para un sitio con características geotécnicas dadas.
-   La estimación de la respuesta sísmica que produce ese movimiento sísmico regional en el sitio de emplazamiento.
-   La identificación de los parámetros de la respuesta sísmica (demanda) para la cual quiero asegurar el cumplimiento de algún criterio de diseño.

Las filosofías de diseño sísmico basadas en la capacidad, que se emplean en la mayoría de los códigos y reglamentos de diseño estructural, limitan la demanda en términos de estados límites últimos o estados límites de servicio y deben segurar que $D \leq C$.

Las filosofías de diseño basadas en la performance (PBEE) por otra parte, limitan la demanda en términos de un conjunto de objetivos específicos de desempeño (distorsiones máximas, asentamientos, etc) que deben cumplirse para diferentes niveles de servicio (construcción, operación, cierre) $\left\{ D_{k}\leq d^{\ast }_{k}\right\}$.

En cualquiera de los marcos de análisis, la ocurrencia de eventos sísmicos es un fenñómeno de naturaleza aleatoria y la demanda y la intensidad sísmica serán por lo tanto variables aleatorias y los estados límite de capacidad o los objetivos de performance sólo podrán cumplirse de manera probabilística. Luego, el diseño óptimo de un sistema deberá asegurar que la probabilidad de excedencia de la demanda sísmica dsea menor a cierto valor objetivo $p^*$. Para lograr este objetivo de diseño basado en la confiabilidad, el modelo deberá incluir dos etapas adicionales

-   La estimación de la tasa anual de ocurrencia de eventos mayores a una cierta intensidad en una región dada.
-   La estimación de la tasa anual en que la demanda sísmica, excede un cierto estado límite

Para poder identificar las limitaciones y desafíos del estado actual de la práctica, se plantea el problema a traves de los pasos que se requieren para el desarrollo de un modelo de estimación de demanda sísmica $G_D(d^*)$ de un sistema dinámico general.

### Planteo del Problema {#planteo-del-problema}

Si asumimos que la demanda sísmica $D$ está relacionada exclusivamente con la ocurrencia de eventos sísmicos durante un período de exposición $T_e$, y que la ocurrencia de estos eventos sigue un proceso de Poisson, la demanda sísmica dependerá del período de exposición $T_e$ y la confiabilidad del diseño puede expresarse numéricamente según $$P_{T_e}\left [D > d^*  \right ]\approx 1-e^{-\lambda_D(d^*) T_e}\leq p^*$$ El parámetro de Poisson $\lambda_D$ es la tasa anual en que la demanda $D$ excede un cierto umbral $d^*$ y depende de la probabilidad de excedencia $P\left [D>d^* \right ]$ de un evento sísmico, y del número de eventos por año $\nu_o$ capaces de producir daño. $$ \lambda_D(d^*) \approx \nu_o P\left [D>d^* \right ] $$

Entendiendo que la respuesta sísmica de un sistema sistema será dependiente del movimiento sísmico del sitio del proyecto, la probabilidad de excedencia $P\left [ D>d^* \right ]$ debe poder condicionarse a algunas características del movimiento sísmico. El planteo tradicional es caracterizar el movimiento sísmico a partir de una medida escalar de intensidad escalar $I=i^*$. Bajo esta hipótesis, la probabilidad de excedencia puede estimarse mediante el teorema de la probabilidad total $$P\left [ D>d^* \right ] \approx \sum^{}_{all\  i^{\ast }}  P\left [D > d^*|I \right ] \ P\left [I=i^*  \right ] \approx G_D(d^*)$$

La frecuencia con la que ocurren eventos de intensidad $I=i^*$ puede obtenerse a partir de la probabilidad de excedencia $P\left [ I>i^* \right ]$ para todos los escenarios posibles de eventos sísmicos en el sitio. La intensidad sísmica del sitio $i^*$ dependerá en general de la distancia del sitio al punto más cercano de la falla $r^*$ y de la magnitud $m^*$ del evento sísmico, el cual está directamente relacionado con el tamaño del área de falla.

Debido a la naturaleza aleatoria asociada a la ubicación de los hipocentros de un terremoto y al tamaño del área de ruptura asociada a durante un evento sísmico, la distancia a la falla $R$ y la magnitud $M$ son variables aleatorias que expresan de manera simplificada la variabilidad temporal y espacial, respectivamente, del movimiento sísmico y la intensidad $i^*$ asociada a un sitio queda definida en términos de una función de excedencia mediante el Teorema de la Probabilidad Total (TPT)

$$P\left [ I>i^* \right ] \approx \sum^{}_{all\  m^{\ast},r^{\ast}}  P\left [I > i^*|\ M,R \right ] \ P\left [M=m^*,R=r^*  \right ] \approx G_I(i^*)$$

En general, las variables aleatorias $R$ y $M$ suelen considerarse *iid* y $P\left [M=m^*,R=r^* \right ] \approx P\left [M=m^*\right ] P\left [R=r^*\right ]$ Existen escenarios sísmicos en donde puedan estar correlacionadas. Por ejemplo, en sitios cercanos a fallas activas, la distancia al punto más cercano de la falla $R$ suele estar correlacionada con la ubicación del área de ruptura y la función de distribución de las distancias requiere del conocimiento de todas las posibles áreas de ruptura, por lo que $P\left [R=r^*,R=r^* \right ] \approx P\left [R=r^*|M=m^*\right ] P\left [M=m^*\right ]$

Luego, la probabilidad de excedencia de un evento sísmico de intensidad $I=i^*$ originado en una falla situada a una distancia aleatoria \$ r\_{min}\^\* \leq R \leq r\_{max}\^\* \$ y una magnitud \$ m\_{min}\^\* \leq M \leq m\_{max}\^\* \$ queda determinada según la función de densidad acumulada $G_I(i^*)$ según

$$ G_I(i^*) \approx \int^{r_{max}^*}_{r_{min}^*}  \int^{m_{max}^*}_{m_{min}^*} G_{I|R,M}(i^*,r,m) \ f_{R|M}(r,m) \ f_M(m) \ dm \ dr $$

La función de densidad $f_I(i^*)$ que define la probabilidad ocurrencia de un evento sísmico de intensidad $I=i^*$ originado en una situada a una distancia comprendida entre \$ r\_{min}\^\* \leq R \leq r\_{max}\^\* \$ y una magnitud comprendida entre \$ m\_{min}\^\leq M \leq m\_{max}\^ \$ queda determinada según $$ f_I(i^*) \approx \left|\frac{\partial G_I(i^*)}{\partial i}\right | \approx \int^{r_{max}^*}_{r_{min}^*}  \int^{m_{max}^*}_{m_{min}^*} \left|\frac{\partial G_{I|R,M}(i^*,r,m)}{\partial i} \right| f_{R|M}(r,m)  f_M(m)  dm dr  $$

Finalmente, la probabilidad de que la demanda sísmica exceda un valor límite $d^*$ dado que ocurrió un evento de intensidad $I=i$ se puede obtener mediante la expresión general:

$$ G_D(d^*) \approx \int^{i_{max}^*}_{i_{min}^*} \int^{r_{max}^*}_{r_{min}^*}  \int^{m_{max}^*}_{m_{min}^*} G_{D|I}(d^*,i) \left | \frac{\partial G_{I|R,M}(i,r,m)}{\partial i} \right |f_{R|M}(r,m)  f_M(m)  dm dr di  $$

El paso siguiente es efectuar algunas hipótesis sobre la ley de distribución de las variables aleatorias condicionadas $D|I$ y $I|R,M$. Si se asume una cierta ley de distribución para las demanda y la intensidad, las CDFs $G_{D|I}(d,i)$ y $G_{I|R,M}(i,r,m)$ puede obtenerse a partir de ajustar los parámetros que determinan las CDF. Los modelos donde las formas funcionales de las distribuciones de probabilidad se conocen, se denominan modelos paramétricos y sólo requieren la determinación de un número finito de parámetros que parametrizan o ajustan esas formas funcionales.

El paso siguiente es buscar una transformación de las variables aleatorias tal que la variable transformada tenga una ley de distribución aproximadamente Normal. La transformación más simple que se ajusta a los problemas de intensidad y demanda asociadas a la ocurrencia de eventos sísmicos, es la transformación logarítmica, que en la práctica equivale a asumir una ley de distribución log-normal para las variables aleatorias. Luego centrar y normalizar, las nuevas variables aleatorias de la demanda e intensidad quedan determinadas según

$$ \epsilon_{D}(d^*,i) \approx  \frac{ln\ d^*-\mu_{ln \ D|I}(i)}{\sigma_{ln \ D} }  \ \ \ \ \ \ \ \ \ \ \  \epsilon_{I}(i^*,m,r) \approx  \frac{ln \ i^*-\mu_{ln \ I|M,R}(m,r)}{\sigma_{ln \ I} } \leq \epsilon_{T}$$

El término $\mu_{lnD|I}(i) \approx ln \ \eta_{D|I}(i)$ es el modelo de predicción del movimiento sísmico (GMPE) y ajusta las intensidades obtenidas de una selección de registros de aceleraciones para diferentes escenarios sísmicos de magnitud y distancia ${M,R}$. Por otra parte, el modelo de demanda condicional $\mu_{ln \ D|I}(i)$ se puede estimar a partir del análisis de un conjunto de registros sísmicos escalados a una intensidad objetivo $i^*$ para los cuales se obtiene un conjunto de respuestas $\{ d_k^*\}$. El modelo más simple de regresión para la mediana condicional puede obtenerse simplemente como la esperanza o valor medio de todas las respuestas

Una de las ventajas de esta transformación es que las CDF $G_{I|R,M}(i^*,r,m)$ y $G_{D|I}(d^*,i)$ pueden definirse explícitamente en términos de la función de densidad normal $\phi(\epsilon^*)$ y la función de densidad acumulada complementaria normal $\tilde\Phi(\epsilon^*)=1-\Phi(\epsilon^*)$ donde $\epsilon^*$ es una variable aleatoria normal normalizada, con valor medio $\mu_{\epsilon}=0$ y desvío $\sigma_{\epsilon}=1$

Cuando se conocen las funciones de distribución de la intensidad y la demanda, la ecuación de diseño del sistema dinámico queda determinada mediante la resolución numérica de la siguiente integral:

$$ G_D(d^*) \approx \int^{i_{max}^*}_{i_{min}^*} \int^{r_{max}^*}_{r_{min}^*}  \int^{m_{max}^*}_{m_{min}^*}  \ \frac{\tilde\Phi \left[ \epsilon_{D}(d^*,i) \right] \phi \left[\epsilon_{I}(i,m,r) \right]  \ f_{R|M}(r,m) \ f_M(m)}{ i \ \sigma_{ln I}} \  dm \ dr \ di \leq \frac {-ln \left(1-p^* \right)}{\nu_o \ T_E}  $$

Las variables aleatorias normalizadas $\epsilon_{D}(d^*,i)$ y $\epsilon_{I}(i^*,m,r)$ dependen indirectamente de los términos de error $\sigma_{ln \ D}$ y $\sigma_{ln \ I}$ controlan toda la incertidumbre del modelo de estimacion de demanda $G_D(d^*)$
