---
# title: "P2"
# author: "Alejandro Verri Kozlowski"
# date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Limitaciones del estado actual de la práctica

### Carcterización del movimiento sísmico

En un planteo paramétrico, los modelos de predicción del movimiento sísmico se basan en estimadores no-sesgados de la mediana condicional $\eta_{I|M,R}(m,r)$ y la varianza $\sigma_{ln \ I|M,R}$ de una medida escalar de intensidad $I=i^*$. Los modelos escalares requiere la elección de una medida óptima de intensidad para caracterizar la relación entre el movimiento sísmico y la demanda sísmica.

La identificación de IM óptimas puede ser abordada a partir de los conceptos de eficiencia y suficiencia. Una medida de intensidad suficiente es aquella para la cual la demanda condicional es condicionalmente independientes de la magnitud $M$ y la distancia $R$ de los sismos seleccionados. Para una IM suficiente, la adición de registros de diferentes M o R no reduce la variabilidad $\sigma_{ln D|I}$. Una IM eficiente por otra parte, es aquella que reporta una variabilidad relativamente pequeña en la demanda sísmica y puede ser cuantificada en el desvío estándar del error aleatorio $\sigma_{ln D|I}$.

Los modelos de predicción del movimiento sísmico se ha concentrado históricamente en la predicción de la aceleracion máxima del terreno $PGA$ y en los últimas dos décadas, se ha generalizado el uso de modelos basadas en ordenadas espectrales $Sa(T)$ de un espectro de respuesta elástico de un oscilador equivalente de un grado de libertad SDOF. En los sistemas dinámicos que pueden asemejarse a un SDOF las aceleraciones espectrales $Sa(T)$ suelen ser medidas eficientes y suficientes para estimar la demanda sísmica en términos de fuerzas y deformaciones elásticas para un cierto rango de períodos. Las estructuras SDOF fuera del régimen elástico, o geoestructuras como taludes y presas de materiales sueltos o relaves, son sistemas dinámicos cuyas propiedades dinámicas varían durante el proceso de deformación y no se disponen medidas de intensidad (escalares) eficientes ni suficientes para estimar la respuesta sísmica

En los sistemas dinámicos en general no es posible identificar una medida de intensidad escalar que sea eficiente y suficiente y la demanda sísmica dependerá de varios aspectos del movimiento sísmico tales como la duración, el contenido de frecuencias de la señal, la energía, etc.

Cuando se formulan modelos de estimación basados en un vector de medidas de intensidad $I=\{I_1,I_2...\}$ la varianza condicional $\sigma_{ln D|I_1,I_2,...}^2$ se reduce considerablemente. En el caso de un planteo paramétrico, la caracterización de las funciones de distribución requiere conocer la mediana y varianza condicional $\mu_{ln \ I_1,I_2,...|M,R}(m,r)$ y $\sigma_{ln \ I_1,I_2,...|M,R}$, y además la matriz de covarianzas $\rho_{i,j}$ que existen entre diferentes medidas de intensidad $\{I_i,I_j \}$ Cuando se emplean más de dos IMs, esta operatoria se vuelve muy engorrosa y por otra parte limita la aplicabilidad del modelo, ya que dos IMs eficientes para un problema dinámico en particular, difícilmente lo sean para otro.

### Respuesta del Sitio

Los registros sísmicos de diferentes regiones del mundo, fueron obtenidos en estaciones sismológicas construidas sobre sitios con diferentes configuraciones geotécnicas.

Los modelos de predicción del movimiento sísmico en general incorporan factores de amplificación de ordenadas espectrales para considerar los efectos locales del sitio en la predicción de la intensidad , dependiente de categorías de suelo basadas en velocidades de onda de corte de los últimos 30 m del estrato. La caracterizacion de los efectos de sitio mediante un único factor basado en categorías de suelo, introduce una gran variabilidad epistémica en la predicción de la respuesta dinámica del sitio y la predicción del movimiento sísmico en superficie, particularmente fuerte en sitios con velocidades de onda de corte promedio menores a 500-700 m/s.

Para reducir esta variabilidad se requiere primermente caracterizar la respuesta del sitio mediante un sistema de clasificación que incorporen otros parámetros escalares mejor correlacionados con las propiedades dinámicas del suelo $\pmb S = \{ S_1, S_2, ... \}$ Y luego, corregir los parámetros que caracterizan el movimiento sísmico en roca basal. Esto equivale en la prácita a introducir un nuevo proxy en la estimación de la demanda,

### Ergodicidad, Estacionareidad y Homocedasticidad

El modelo de demanda sísmica $G_D(d^*)$ asume que la variable aleatoria condicionada $\epsilon_{I}(i^*,m,r)$ tiene una distribución normal con parámetros $\sigma_{ln I}^2$ y $\mu_{ln \ I|M,R}(m,r)$ constantes para un escenario sísmico $\{M,R\}$ dado. Es decir, supone un proceso aleatorio en la cual estos parámetros no varían en el tiempo y por otra parte, que son invariantes del registro sísmico. En otras palabras, el empleo de modelos paramétricos para caracterizar las variables aleatorias $I/M,R$ implica en la práctica que todas las series temporales (aleatorias) de la región analizada, son una realización de un único proceso aleatorio ergódico que mantiene invariantes las propiedades de sus funciones de distribución.

La ergodicidad desempeña un papel fundamental en las estimaciones de las magnitudes estadísticas, ya que garantiza que los momentos $\sigma_{ln I}^2$ y $\mu_{ln \ I|M,R}(m,r)$ de las series temporales sean estimadores insesgados de la esperanza y la varianza de las funciones de distribución $G_{I|M,R}$

Los modelos de predicción del movimiento sísmico $\mu_{ln \ I|M,R}(m,r)$ se ajustan a través de registros de aceleraciones correspondientes a diferentes escenarios sísmicos de magnitud y distancia $\{M,R\}$ En una situación ideal, un conjunto de registros sísmicos de aceleraciones de una región con una larga historia de sismicidad instrumental, abarcarían todos los escenarios $\{M,R\}$ requeridos para el modelo empírico. En la práctica, dificilmente una región dispone de un número suficiente de registros sísmicos, particularmente de movimiento fuerte, que aporten estos escenarios y generalmente se emplean datasets que incorporan registros de diferentes regiones del mundo, que comparten alguna caracerística con la región de análisis. Esta limitación en la selección de los datasets incorpora una gran incertidumbre aleatoria ya que cualquier diferencia que exista entre el medio de propagación, los espectros de frecuencias de la fuente, la respuesta del sitio, etc, se manifestará como una mayor varianza $\sigma_{ln I}^2$.

La varianza del modelo de estimación del movimiento sísmico $\sigma_{ln \ I}$ es una constante que no depende del escenario sísmico de magnitud y distancia $\{M,R\}$ Esto es una consecuencia de haber adotpado un modelo paramétrico que asumió una cierta forma funcional para la función de distribución (normal). Los modelos GMPE más avanzados, tienen términos de error no menores a $\sigma_{ln \ I}\approx0.6$ lo que equivale en la práctica a asumir una variabilidad no menor al 80% para la predicción de la intensidad en un escenario dado. Para reducir esta variabilidad se requieren relajar la hipótesis de homocedasticidad mediante una varianzas condicionales variables (GARCH) y modelos no-paramétricos, en los cuales no se requiere de antemano ninguna forma funcional explícita para las funciones de distribución (distribution-free models) del modelo $G_{I|R,M}(i,r,m)$ y $G_{D|I}(d^*,i)$

### Selección de Sismos

El estado de la práctica actual, se basa en un modelo de predicción de intensidad y demanda para sistemas elásticos con respuesta sísmica conocida. En los sistemas dinámicos más complejos, como las geoestructuras de materiales sueltos, o incluso estructuras similares a un SDOF fuera del régimen elástico, la respuesta sísmica depende en general del contenido de frecuencias y duración de los registros sísmicos, es decir dependen del registro sísmico.

En estos sistemas, la respuesta sísmica sólo puede obtenerse mediante modelos numéricos y la caracterización de la función de distribución de la demanda sísmica $G_{D|I}(d,i^*)$ se obtiene a partir del análisis de un número grande de registros sísmicos escalados a la intensidad sísmicica objetivo $I=i^*$.

Sin embargo, no es posible desagregar de la intensidad condicional $I|M,R$ una muestra representativa de la demanda sísmica, y en teoría se requiere el análisis de un gran número de regisros sísmicos para obtener los parámetros de la función de distribución de la demanda sísmica $G_{D|I}(d,i^*)$ . En la práctica, debido principalmente al costo computacional, sólo un número reducido de registros sísmicos suele analizarse y los estimadores son sesgados y se requieren metodologías de selección de registros sísmicos para identificar aquellos que controlan la demanda.

### Resumen

-   La variabilidad de la demanda y en consecuencia, la incertidumbre de la probabilidad de falla de un diseño, está controlada por el error del modelos de predicción del movimiento sísmico y el error de predicción de la demanda sísmica.

-   La caracterización del movimiento sísmico en términos de una medida escalar de intensidad, limita la eficiencia de cualquier modelo de predicción de la demanda sísmica, particularmente en problemas que no son asemejables a un SDOF en respuesta elástica

-   La hipótesis de normalidad en las funciones de distribución de la intensidad (escalar) condicional, implica una varianza constante (homocedásticidad) para todos los escenarios sísmicos y afecta fuertemente el término de error aleatorio del movimiento sísmico, particularmente cuando se combinan registros sísmicos de diferentes regiones del mundo

-   Los efectos de sitio sólo son pueden ser considerados a partir de un factor de amplificación empírico de las ordenadas espectrals basado en la velocidad de corte de los últimos 30 m del estrato $\tilde S_a(T) \approx AF(V_{S.30}) \ S_a(T)$ , el cual no permite correlacionar adecuadamente los efectos del sitio con el contenido de frecuencias de los registros sísmicos en superficie, y aporta una gran variabiliad adicional en las caracteristicas del movimiento sísmico en superficie, particularmente cuando existen estratos profundos de suelos de baja rigidez sometidos a movimiento fuerte del terreno.

-   En los sistemas dinámicos en general, los estimadores de la demanda sísmica condicional $D|I$ son siempre sesgados,y el sesgo dependerá dependiendo del número de registros sísmicos que puedan analizarse.
