---
# subtitle: "Propuesta de Tesis Doctoral"
# title: "Generación automática de modelos para la estimación de la respuesta sísmica de sistemas dinámicos complejos"
# author: "Postulante: Alejandro Verri Kozlowski"
# date: "4/14/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Enfoque propuesto

### Motivación. Limitaciones del estado actual del arte. 

En el estado de la práctica actual de la predicción de la respuesta sísmica, la variabilidad de la demanda y en consecuencia, la incertidumbre de la probabilidad de falla de un diseño, está controlada por el error del modelos de predicción del movimiento sísmico y el error de predicción de la demanda sísmica.

La caracterización del movimiento sísmico en términos de una medida escalar de intensidad, limita la eficiencia de cualquier modelo de predicción de la demanda sísmica, particularmente en problemas que no son asemejables a un SDOF en respuesta elástica

La hipótesis de normalidad en las funciones de distribución de la intensidad (escalar) condicional, implica una varianza constante (homocedásticidad) para todos los escenarios sísmicos y afecta fuertemente el término de error aleatorio del movimiento sísmico, particularmente cuando se combinan registros sísmicos de diferentes regiones del mundo

El estado de la práctica actual considera la influencia de los efectos del sitio a partir de factores de amplificación de ordenadas espectrales empíricos basados en la velocidad de onda de corte Vs30, que es un parámetro geotécnico pobremente correlacionado con la respuesta dinámica del sitio, y aporta una gran variabiliad adicional en las caracteristicas del movimiento sísmico en superficie, particularmente cuando existen estratos profundos de suelos de baja rigidez sometidos a movimiento fuerte del terreno.

### Enfoque propuesto. Objetivos Generales 

El propósito del presente trabajo de investigación es la formulación de una metodología general para generación automática de modelos robustos de estimación de respuesta sísmica de sistemas dinámicos complejos, entendiendo a robustos a formulaciones heterocedásticas y no-paramétricas (distribution-free), y automáticos en el sentido de la inferencia de datos a partir del aprendizaje automático (Machine Learning) de la respuesta obtenida mediante modelos numéricos complejos

Para llevar a cabo este propósito se requiere en primer lugar, caracterizar el movimiento sísmico en la roca basal (es decir, desagregando la influencia del sitio) mediante series temporales parametricas, de modo tal de obtener una función de distribución en función de un conjunto reducido de parámetros $\psi = \{ \psi_1,\psi_2,... \}$, que serán característicos de los sismos de una región objetivo. Según este enfoque, cualquier medida de intensidad del movimiento sísmico, puede caracterizarse mediante una variable aleatoria con una función de distribución dada por $f_{I|\Psi}(\psi_1,\psi_2,...)$ y el peligro sísmico de una región y un sitio dado, quedar expresado para cualquier medida de intensidad según. $$ f_{\Psi}(\psi_1^*,\psi_2^*,...) \approx \int^{r_{max}^*}_{r_{min}^*}  \int^{m_{max}^*}_{m_{min}^*} f_{\Psi|R,M}(\psi_1^*,\psi_2^*,...,r,m) \  f_{R|M}(r,m)\  f_M(m) \ dm \ dr $$

Luego, el paso siguiente será incorporar los efectos del sitio en la amplitud y el contenido de frecuencias de movimiento sísmico en superficie, a partir de un modelo de respuesta dinámica del sitio. Para ello, se deberán re-caracterizar los sismos en superficie mediante series paramétricas y correlacionar los parámetros en superficie $\Theta = \{ \Theta_1,\Theta_2,... \}$, con los parámetros de roca basal $\Psi = \{ \Psi_1,\Psi_2,... \}$, según una nueva variable aleatoria con una distribución $f_{\Theta|\Psi,S}(\psi_1,\psi_2,...,s)$ donde $S$ representa los parámetros geotécnicos y dinámicos del sitio. Este planteo implica en la práctica mantener una base de datos de series temporales paramétricas $\Psi = \{ \Psi_1,\Psi_2,... \}$, desagregada por región, mecanismo y tipo de suelo.

Para reducir la variabilidad asociada a las características geotécnicas y dinámicas del suelo, se requiere una caracterizacion alterntiva del sitio, basada no solamente en las velocidades de corte en los últimos 30 m de suelo $V_{S.30}$ sino en otros parámetros mejor correlacionados con la respuesta global de sitio, tales el período natural del sitio $T_S$, el espesor del estrato $H_S$ y la rigidez al corte promedio $G_S$. Luego, las funciones de distribución del movimiento del terreno en superficie serán en la forma

$$ f_{\Theta}(\theta^*) \approx \int^{r_{max}^*}_{r_{min}^*}  \int^{r_{max}^*}_{r_{min}^*}  \int^{m_{max}^*}_{m_{min}^*}  f_{\Theta|\Psi,S}(\theta^*,\psi,s) \ f_{\Psi|R,M}(\psi,r,m) \  f_{R|M}(r,m)\  f_M(m) \ dm \ dr $$

donde $\psi = \{ \psi_1,\psi_2,... \}$ es un vector de parámetros que equivalentes a un registro sísmico en roca basal y $\theta^* = \{ \theta_1^*,\theta_2^*,... \}$, a otro en superficie

-   Incorporar los efectos del sitio en los parámetros del movimiento sísmico en roca basal, mediante un modelo de respuesta de sitio basado de las propiedades dinámicas del estrato $S=\{T_S,H_S,V_S\}$

El análisis de datos requiere la implementación de una base de datos de registros sísmicos en roca basal que estén caracterizados mediante conjunto reducido de parámetros $\psi = \{ \psi_1,\psi_2,... \}$ basados en modelos paramétricos de series temporales.

La intensidad del movimiento sísmico puede expresarse como una variable aleatoria independiente

$$.}  P\left [I > i^*|\Psi_1,\Psi_2,... \right ] \ P\left [\Psi_1=\psi_1^*,\Psi_2=\psi_2^*, ...  \right ] \approx G_D(d^*)$$

### Objetivos

Para definir las etapas anteriormente descritas, se requieren como m´

$P\left [ D>d^* \right ] \approx \sum^{}_{all\  i^{\ast }} P\left [D > d^*|\Phi_1,\Phi_2,... \right ] \ P\left [\Phi_1=\phi_1^*,\Phi_2=\phi_2^*, ... \right ] \approx G_D(d^*)$ Este objetivo será abordado en el Capítulo I, que se enfocará en el tratamiento y clasificación de los datos que serán parte de los modelos de inferencia, y tendrá las siguientes etapas y objetivos:

-   La compilación de datos, que consistirá básicamente en compilar conjuntos de datos de registros sísmicos pertenecientes a diferentes regiones del mundo y medidos en estaciones bajo diferentes configuraciones geotécnicas y luego

-   La regularización de datos, que consistirá en procesar los registros sísmicos para eliminar registros corruptos, resamplear y unificar las tasas de muestreo, remover tendencias, aplicar filtros e integrar las series temporales para obteer velocidades y desplazamientos

-   La normalización de datos, que consistirá en desagregar registros en diferentes escenarios sísmicos de magnitud y distancia a la fuente $\{M,R\}$ y luego desagregar los efectos de sitio en las series temporales, es decir, obtener una expresión del movimiento sísmico en roca basal.

-   La parametrización de datos . El objetivo de esta etapa es identificar los parámetros asociados a un modelo dinámico equivalente $\psi = \{ \psi_1,\psi_2,... \}$ mediante el análisis paramétrico de series temporales no-estacionarias. Esta es la etapa define uno de los aportes más importantes del trabajo, ya que establece una representación paramétrica de los registros sísmicos

-   La clasificación de los datos. El objetivo de esta etapa es analizar parámetros dinámicos $\psi = \{ \psi_1,\psi_2,... \}$ e identificar grupos (clústers) de registros sismicos (desagregados por escenarios) expresados en términos de sus mediante la implementación de un conjunto de métricas adecuadas para series temporales paramétricas.

El segundo capítulo estará enfocado en la predicción del movimiento sísmico

-   Movimiento sísmico en roca basal: El objetivo de esta etapa será formular un modelo simple de predicción del movimiento sísmico a nivel de roca basal en términos de los parámetros . Para cada escenario sísmico, el objetivo de esta etapa será obtener las funciones de distribución del movimiento sísmico $f_{\Theta|M,R}\left(m,r \right)$ expresado en términos de los sismos característicos de la región $\Theta = \{ \Theta_1,\Theta_2,... \}$

-   Respuesta de Sitio. La etapa siguiente consistirá en incorporar los efectos del sitio en los parámetros dinámicos obtenidos en la etapa anterior. El objetivo de esta etapa será

-   mediante una nueva variable aleatoria condicoinal $S|T_s,H_s,V_s$. El objetivo de esta etapa será definir un sistema de clasificación de perfiles geotécnicos basados en un factor aleatorio $S$ que tendrá una función de distribución $f_{S|T_s,H_s,V_s}(t,h,v)$ con mediana condicional $\eta_{S|T_s,H_s,V_s}(t,h,v)$ y una varianza $\sigma_{S|T_s,H_s,V_s}^2$ donde $T_s$ es el perído propio del sitio, $H_s$ es el espesor del estrato hasta la roca basal y $V_s$ es la velocidad de onda de corte promedio de todo el estrato, que es una medida indirecta de la rigidez al corte del estrato .

2\. Mediante esta nueva variable aleatoria, el objetivo siguiente será caracterizar la función de distribución del movimiento sísmico en superficie, según en la forma

La etapa siguiente consistirá en incorporar los efectos del sitio a partir de una funcion de distribución $f_{\Psi|\Theta,S}\left(\theta,s \right)$ donde $\Psi|\Theta,S$ es un vector de variables aleatorias $\Psi = \{ \Psi_1,\Psi,... \}$ que representa las propiedades del movimiento sísmico en superficie, y estará condicionada a los parámetros de la región $\Theta$ y a los parámetros que caracterizan al sitio $S$ La etapa siguiente será estimar la demanda sísmica del sistema dinámico objetivo, a partir de los parámetros de movimiento sísmico en roca basal y de

La etapa final, deberá integrar las etapas anteriores en un modelo generalizado de estimación de la demanda sísmica, basado en los sismos característicos de la región que fueron parametrizados según un conjunto de parámertros, y

### Aportes

*\_ codigos definen PSHA en terminos de Sa\_*

Los aportes que resultarán del desarrollo de este trabajo de investigación serán los siguientes: La identificación de un conjunto óptimo de parámetros dinámicos y medidas de intensidad que caracterizan los movimientos sísmicos de una región combinada con la implementación de metodologías de inferencia no-paramétricas permitirán sentar las bases para la formulación de una nueva generación de modelos de predicción de intensidad y demanda de alta eficiencia, particularmente útiles en el contexto del diseño sísmico basado en la confiabilidad. ¡Luego, el principal aporte de este trabajo será una metodología de generación automática de modelos de predicción de respuesta sísmica. El procesamiento y análisis de series temporales, aportará en primer lugar una base de datos de acceso público de varios millones de registros sísmicos inferidos en roca basal, que incluirán como característica distintiva de las bases disponibles en la actualidad, los parámetros dinámicos (features) de cada región. La publicación de esto datos habilita automáticamente el desarrollo de modelos de predicción de intensidad más sofisticados en cualquier región del mundo en donde se dispongan registros sísmicos de referencia. Por otra parte, los algoritmos de procesamiento, regularización, caracterización y clasificación de registros sísmicos serán publicados bajo licencia de código abierto en una librería en lenguaje R, y en un paquete de lenguaje Wolfram (Mathematica).

### 

### Referencias

Parte I: Procesamiento de Series Temporales

Andreas Antoniou, P. D. (2018). Digital Filters: Analysis, Design, and Signal Processing Applications. Arias, J., & Blázquez, R. (2008). Accuracy Of Time Integration Procedures For Seismic Response Of Linear Oscillators. 14th World Conference on Earthquake Engineering. Charara, I. (2019). Seismic response of n-layered soil : Exact analytical closed-form solution. 1698--1706. Enochson, L. D., & Otnes, R. K. (1965). Digital spectral analysis. In SAE Technical Papers. Faccioli, E., Vanini, M., & Frassine, L. (2002). "Complex" site effects in earthquake ground motion, including topography. 12th European Conference on Earthquake Engineering, Paper No.844, 23. Gavin, H. P. (2018). Numerical Integration in Structural Dynamics. Giron-Sierra, J. M. (2017). Digital Signal Processing with Matlab Examples, Volume 3. In Electronics {&} Communications Engineering Journal (Vol. 5, Issue 1). Graizer, V., & Commission, U. S. N. R. (2016). Determination of the true ground displacement by using strong motion records. January 1979. Hancock, J., & Bommer, J. J. (2005). The effective number of cycles of earthquake ground motion. Earthquake Engineering and Structural Dynamics, 34(6), 637--664. <https://doi.org/10.1002/eqe.437> Heinzel, G., Rüdiger, A., & Schilling, R. (2002). Spectrum and spectral density estimation by the Discrete Fourier transform (DFT). MPG Publication Repository, 1--84. Johnson, S. G., Mathematics, M. I. T. A., & April, C. (2011). Notes on FFT-based differentiation. 1--11. L., R. J., Martinez, M., & J.Muñoz. (n.d.). Digital Signal Processing with Kernel Methods. Last, M., Kandel, A., & Bunke, H. (n.d.). Data Mining in Time Series Databases. Lee, E., & Varaiya, P. (2003). Sampling and Reconstruction. Lee, H. S., Hong, Y. H., & Park, H. W. (2010). Design of an FIR filter for the displacement reconstruction using measured acceleration in low-frequency dominant structures. November 2009, 403--434. Li, H., Zheng, S., Song, C., & Feng, Q. (2013). Recovering Seismic Displacements from Underground Strong-Motion Acceleration Records of the 2011 M W 9 . 0 Tohoku Earthquake in Japan. 674, 1418--1422. Margrave, G. F. (2006). Methods of Seismic Data Processing. Rainer, J. (1986). Applications of the Fourier transform to the processing of vibration signals. Building Research Note, 233, 24. Tsai, N. C., & Housner, G. W. (1970). Calculation of surface motions of a layered half-space. Bulletin - Seismological Society of America, 60(5), 1625--1651. Valley, G. (n.d.). Peak Particle Velocity vs . the Richter Scale.

Parte II: Análisis, caracterización y clasificación de Series Temporales

Cakmak, A. S., & Sherif, R. I. (n.d.). Parametric Time Series Models for Earthquake Strong Ground Motions and Their Relationship to Site Parameters. Chang, M. K., Kwiatkowski, J. W., Nau, R. F., Oliver, R. M., & Pister, K. S. (1979). ARMA models for earthquake ground motions. Conte, J. P., Pister, K. S., & Mahin, S. A. (1992). Non-stationary ARMA modeling of seismic motions. Soil Dynamics and Earthquake Engineering, 11(7), 411--426. [https://doi.org/10.1016/0267-7261(92)90005-X](https://doi.org/10.1016/0267-7261(92)90005-X){.uri} Dolan, K. T., & Spano, M. L. (2001). Surrogate for nonlinear time series analysis. Physical Review E - Statistical Physics, Plasmas, Fluids, and Related Interdisciplinary Topics, 64(4), 6. <https://doi.org/10.1103/PhysRevE.64.046128> Kantz, H., & Shreiber, T. (2003). Nonlinear Time Series Analysis. Cambridge. Kassambara, A. (2017). Practical Guide To Cluster Analysis in R - Unsupervised Machine Learning. Kassambara, A. (2017). Practical Guide to Principal Component Methods in R Multivariate Analysis Kassambara, A. (2017). Practical Guide To Principal Component Methods in R: PCA, M (CA), FAMD, MFA, HCPC, factoextra. Sthda, 2, 1--155. Kaufman, L., & Rousseeuw, P. J. (2005). Finding Groups in Data - An Introduction to Cluster Analysis. Kloke, J., & Mckean, J. W. (2014). The R Series Statistics Nonparametric Statistical Methods Using R. Chapman and Hall/CRC. Kozin, F. (1988). Autoregressive moving average models of earthquake records. Probabilistic Engineering Mechanics, 3(2), 58--63. [https://doi.org/10.1016/0266-8920(88)90016-1](https://doi.org/10.1016/0266-8920(88)90016-1){.uri} Maharaj, E. A., D'Urso, P., & Caiado, J. (2019). Time Series Clustering and Classification. In Time Series Clustering and Classification. <https://doi.org/10.1201/9780429058264> Montero, P., & Vilar, J. A. (2014). TSclust: An R package for time series clustering. Journal of Statistical Software, 62(1), 1--43. <https://doi.org/10.18637/jss.v062.i01> Percival, D. B. (1992). Simulating Gaussian Random Processes with Specified Spectra. Computing Science and Statistics, 24, 534--538. Percival, D. B., & Walden, A. T. (2020). Spectral Analysis for Univariate Time Series. In Spectral Analysis for Univariate Time Series. <https://doi.org/10.1017/9781139235723> Popescu, T. D., & Demetriu, S. (1990). Analysis and simulation of strong earthquake ground motions using ARMA models. Automatica, 26(4), 721--737. [https://doi.org/10.1016/0005-1098(90)90049-N](https://doi.org/10.1016/0005-1098(90)90049-N){.uri} Schreiber, T. (1998). Constrained randomization of time series data. Physical Review Letters, 80(10), 2105--2108. <https://doi.org/10.1103/PhysRevLett.80.2105> Schreiber, T., & Schmitz, A. (2000). Surrogate time series. Physica D: Nonlinear Phenomena, 142(3--4), 346--382. [https://doi.org/10.1016/S0167-2789(00)00043-9](https://doi.org/10.1016/S0167-2789(00)00043-9){.uri} Spiegel, S. (2015). Time Series Distance Measures: Segmentation, Classification, and Clustering of Temporal Data. 211. Wilks, D. S. (2011). Principal Component (EOF) Analysis. In International Geophysics (Vol. 100). <https://doi.org/10.1016/B978-0-12-385022-5.00012-9>

Parte III: Predicción de la respuesta sísmica

Baker, J. W. (2007). Correlation of ground motion intensity parameters used for predicting structural and geotechnical response. Proceedings of the 10th International Conference on Applications of Statistics and Probability, 501--502. Bertero, R. D., & Asce, M. (n.d.). ACCEPTABILITY CHECKS FOR PERFORMANCE-BASED SEISMIC DESIGN. 1--17. Chambers, M. J. (1995). The simulation of random vector time series with given spectrum. Mathematical and Computer Modelling, 22(2), 1--6. [https://doi.org/10.1016/0895-7177(95)00106-C](https://doi.org/10.1016/0895-7177(95)00106-C){.uri} Conte, J. P., & Peng, B. F. (1997). Fully nonstationary analytical earthquake ground-motion model. Journal of Engineering Mechanics, 123(1), 15--24. [https://doi.org/10.1061/(ASCE)0733-9399(1997)123:1(15)](https://doi.org/10.1061/(ASCE)0733-9399(1997)123:1(15)){.uri} Conte, J. P., Pandit, H., Stewart, J. P., & Wallace, J. W. (2003). Ground motion intensity measures for performance-based earthquake engineering. 2(1), 1465--1472. Dabaghi, M., & Kiureghian, A. Der. (2014). Stochastic Modeling and Simulation of Near-Fault Ground Motions for Performance-Based Earthquake Engineering. Geisser, S. (n.d.). Models of Parametric Statistical Inference. Wiley. Hardle, W., & Mammen, E. (1993). Comparing Nonparametric Versus Parametric Regression Fits. The Annals of Mathematical Statistics, 21(4), 1926--1947. Hollander, M., Wolfe, D. A., & Chicken, E. (n.d.). Nonparametric Statistical Methods. Wiley. Lee, V., & Trifunac, M. (1995). CE 95-03 - Frequency Dependent Attenuation Function. Perez Ruiz, D. A. (2016). Bayesian Nonparametric Data Analysis. In International Statistical Review (Vol. 84, Issue 1). <https://doi.org/10.1111/insr.12168> Rathje, E. M., Abrahamson, N. A., & Bray, J. D. (1998). Simplified frequency content estimates of earthquake ground motions. Journal of Geotechnical and Geoenvironmental Engineering, 124(2), 150--158. [https://doi.org/10.1061/(asce)1090-0241(1998)124:2(150)](https://doi.org/10.1061/(asce)1090-0241(1998)124:2(150)){.uri} Rathje, E. M., & Saygili, G. (2008). Probabilistic seismic hazard analysis for the sliding displacement of slopes: Scalar and vector approaches. Journal of Geotechnical and Geoenvironmental Engineering, 134(6), 804--814. [https://doi.org/10.1061/(ASCE)1090-0241(2008)134:6(804)](https://doi.org/10.1061/(ASCE)1090-0241(2008)134:6(804)){.uri} Rathje, E. M., Faraj, F., Russell, S., & Bray, J. D. (2004). Empirical Relationships for Frequency Content Parameters of Earthquake Ground Motions. Earthquake Spectra, 20(1), 119--144. <https://doi.org/10.1193/1.1643356> Rathje, P. E. M., & Ph, D. (2010). Ground Motion Prediction Equations and Seismic Hazard Assessment. November. Ruiz, S., & Saragoni, R. (2002). Formulas De Atenuación Para La Subducción De Chile Considerando Los Dos Mecanismos De Sismogenesis y los efectos del Suelo. Achisina, 1985. Scherbaum, F., Delavaud, E., & Riggelsen, C. (2009). Model selection in seismic hazard analysis: An information-theoretic perspective. Bulletin - Seismological Society of America, 99(6), 3234--3247. <https://doi.org/10.1785/0120080347> Shin, G., & Song, O. (2016). A Time-Domain Method to Generate Artificial Time History from a Given Reference Response Spectrum. Nuclear Engineering and Technology, 48(3), 831--839. <https://doi.org/10.1016/j.net.2016.01.023> Sprent, P., & Smeeton, N. C. (2007). Applied Nonparametric Statistical Methods. Tuan, P. D. (1984). a Note on Some Statistics Useful in Identifying the Order of Autoregressive Moving Average Model. Journal of Time Series Analysis, 5(4), 273--279. <https://doi.org/10.1111/j.1467-9892.1984.tb00393.x> Vanmarcke, E. H. (1996). Random Process in Earthquake Engineering. 11th World Conference on Earthquake Engineering.
