---
# subtitle: "Propuesta de Tesis Doctoral"
# title: "Generación automática de modelos para la estimación de la respuesta sísmica de sistemas dinámicos complejos"
# author: "Postulante: Alejandro Verri Kozlowski"
# date: "4/14/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Organización y Objetivos

### Objetivos generales

El objetivo final del presente trabajo es desarrollar una metodología robustaa para la estimación de la demanda sísmica probabilística de sistemas dinámicos complejos 

El primer objetivo se enfocará en los datos y consistirá en establecer metodologías de caracterización y clasificación de registros sísmicos, basadas en modelos dinámicos de series paramétricas. Las metodologías de caracterización deberá basarse en el análisis de millones de acelerogramas en roca basal, que puedan ser desagregados segun diferentes escenarios sísmicos de intensidad, y requieren la formulación de bases de datos de movimiento sísmico en roca basal. Las metodologías de clasificación deberán permitir identificar registros sísmicos de un sitio particular y poder asociarlo a un grupo (cluster) de sismos característicos de regiones similares.

El segundo objetivo se enfocará en la predicción y consistirá en establecer los requisitos que deberá un modelo robusto de predicción del movimiento y la demanda sísmica que incluya los sismos de diseño de una región y las características geotécnicas particulares de un sitio dado. En esta etapa se requieren metodologías específicas que permitan integrar la respuesta dinámica de modelos numéricos complejos FEM para la estimación de la respuesta sísmica de sistemas complejos

### Organización y Objetivos específicos

Atendiendo los objetivos fundamentales, el trabajo de Tesis estará dividido en dos partes principales.

#### Parte I:

La primera parte del trabajo estará enfocada básicamente en el tratamiento de los datos y tendrá los siguientes objetivos:

-   La compilación de datos, que consistirá básicamente en compilar conjuntos de registros sísmicos pertenecientes a diferentes regiones del mundo y medidos en estaciones bajo diferentes configuraciones geotécnicas y luego, el tratamiento de datos, que consistirá en procesar los registros sísmicos para eliminar registros corruptos, resamplear y unificar las tasas de muestreo, remover tendencias, aplicar filtros e integrar las series temporales para obteer velocidades y desplazamientos. Este objetivo será abordado en el capítulo 1

-   La normalización de datos, que consistirá en desagregar registros en diferentes escenarios sísmicos de magnitud y distancia a la fuente $\{M,R\}$ y desagregar los efectos de sitio para obtener los acelerogramas del movimiento sísmico a nivel de roca basal. Este objetivo será abordado en el capítulo 2.

-   La parametrización de datos, que se ocupará de identificar los parámetros asociados a un modelo dinámico equivalente $\psi = \{ \psi_1,\psi_2,... \}$ mediante el análisis paramétrico de series temporales no-estacionarias. Esta es la etapa define uno de los aportes más importantes del trabajo, ya que establece una representación paramétrica de los registros sísmicos. Este objetivo será abordado en el capítulo 3

-   La clasificación de los datos, que analizará los diferentes conjuntos de parámetros dinámicos $\psi = \{ \psi_1,\psi_2,... \}$ e identificará grupos (clústers) de registros sismicos (desagregados por escenarios) mediante la implementación de un conjunto de métricas adecuadas para series temporales paramétricas. Este objetivo será abordado en el capítulo 4

#### Parte II

La segunda parte del trabajo estará enfocado en la predicción del movimiento sísmico y la demanda sísmica y tendrá los siguientes objetivos y etapas

-   Formular un modelo simple de predicción del movimiento sísmico a nivel de roca basal en términos de los parámetros . Para cada escenario sísmico, el objetivo de esta etapa será obtener las funciones de distribución del movimiento sísmico $f_{\Psi^L|M,R}\left(m,r \right)$ expresado en términos de los sismos característicos de la región $\Psi^L = \{ \Psi_1^L,\Psi_2^L,... \}$. Este objetivo será abordado en el capítulo 5

-   Definir un sistema de clasificación de sitios a partir de los parámetros dinámicos que controlan la respuesta del sitio, $S = \{T_s,H_s,V_s\}$ donde $T_S$ es el perído propio del sitio, $H_S$ es el espesor del estrato hasta la roca basal y $V_S$ es la velocidad de onda de corte promedio de todo el estrato, que es una medida indirecta de la rigidez al corte del estrato. Este objetivo será abordado en el capítulo 6

-   Definir un modelo general de predicción de la demanda sísmica basada en los sismos característicos de la regi $\pmb\Psi^L$y en un factor de sitio $S$. Este objetivo será abordado en el capítulo 7

-   Presentar una aplicación de la metodología propuesta a un problema de diseño sísmico basado en la performance, para una presa de materiales sueltos de 140 m de altura situada en una zona zísmica de alta actividad, y donde sólo se disponen de un conjunto reducido de registros sísmicos de movimiento fuerte.

## Aportes

El planteo propuesto aportará algunas soluciones a las limitaciones del estado actual de la práctica.

En primer lugar, la identificación de un conjunto reducido de parámetros dinámicos *i.i.d.* que caracterizan los movimientos sísmicos de una región permitirá definir una familia de métodos de predicción basada ya no únicamente en una medida de intensidad escalar del movimiento sísmico (que suele ser insuficiente e ineficiente) sino además en las características dinámicas de las series temporales. Si bien la caracterización paramétrica de series temporales es un concepto que data de la década del '80, la disponibilidad de una base de datos de cientos de miles de registros sísmicos de diferentes regiones del mundo, permitirá emplear metodologías basadas en aprendizaje estadístico (machine-learning) no supervisado que aporten nueva luz sobre un problema extremadamente complejo de abordar a través de modelos físicos

El empleo de métodos de predicción no-paramétricos (distribution-free) por otra parte, relaja alguna de las hipótesis de las metodologías paramétricas (como la homocedasticidada) y permite incorporar modelos más eficientes (menor error cuadrático medio). Por otra parte, la desagregación de los efectos del sitio en los modelos de predicción del movimiento sísmico, resultan en modelos mucho más eficientes y reducen o limitan fuertemente la propagación de la incertidumbre epistémica del efecto del sitio

Luego, el principal aporte de este trabajo será una metodología de generación automática de modelos de predicción de respuesta sísmica.

El procesamiento y análisis de series temporales, aportará una base de datos de acceso público de varios millones de registros sísmicos inferidos en roca basal, que incluirán como característica novedosa los metadatos asociados a los parámetros dinámicos (features) de cada registro y los sistemas de clasificación de cada grupo (Región, Mecanismo, etc).

La publicación de estos datos en formatos de librerías de código abierto en lenguaje R, habilita automáticamente el desarrollo de modelos de predicción de intensidad más sofisticados en cualquier región del mundo en donde se dispongan registros sísmicos de referencia.

Alejandro Verri Kozlowski. Mendoza, Abril de 2021

### 

### 
